### ISSUE TITLE
Plugin doesn't work with groupedBars (plugin: flot.orderBars)

### ISSUE THREAD

**Issue by tksumanth1994** [winne27/flot-valuelabels#4]
v1.5 doesn't work properly with flot.orderBars. The labels come at the center of both bars instead for coming on top of each bar.
<img width="753" alt="screenshot 2016-03-15 12 56 22" src="https://cloud.githubusercontent.com/assets/4353562/13770478/49234a92-eaad-11e5-824c-5d87f32c0bd0.png">

**Comment by winne27** [comment]
can you post the source code of the above diagramm for testing purpose.

**Comment by VojtechH** [comment]
Here is a simple example: https://jsfiddle.net/VojtechH/3e74bnzj/4/

**Comment by winne27** [comment]
See the bottom of main page of this plugin. There is an example how to use valuelabels with order.bars together. The trick is: just using the valuelabel options xoffset and yoffset to adjust the labels for every bar group different.

An automatic solution in the current flow of flot and plugins I don't see, because for every bar group valuelabel function is called seperatly and there is no information how many groups exist. So it is not possible to calculate the necessary offsets.
